### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by hdunderscore** [JSandusky/UrhoAngelscriptIDE#5]
I can't seem to get compile errors to be reported, every build is reported as successful.

I tried to dig into this a little myself, if I allow the window to pop open/stop the stdout redirect I can definitely see the errors. 

When stepping through the code, the output from ScriptCompiler simply doesn't appear to be received -- instead I get the message for the compile file:
from `pi_OutputDataReceived` : `Compiling script file F:\_GameJams\Teacart 1k\Game\Resources\Scripts\main.as`

Neither single file nor multi file compile reports errors.

Maybe I didn't follow instructions correctly, eg I didn't do this yet:

    It's recommended to modify your scriptcompiler to generate the dump files AFTER first compiling the code. This way the header dump will contain definitions for the script classes, functions, and variables found in your files.

Thanks

**Comment by JSandusky** [comment]
Is your compiler relatively recent? There were uses with PrintUnicode in Urho3D's ProcessUtils, piping unicode doesn't work.

It should work out of the box ever since this commit (back on April 15): https://github.com/urho3d/Urho3D/commit/ff8f4b75255de42ac41d6c37b24cf3e0cc3df0ee

---

I need to remove that sentence, it's no longer needed or recommended now that it scans arbitrary angelscript code to get details about script code for type-info, type/function locations, etc.

**Comment by hdunderscore** [comment]
That probably should have been obvious, but that was the issue!

Thanks.
